name: roeah_ruchani_app
description: roeah_ruchani_app.
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  page_transition: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon" 
  image_path: "assets/images/icon/icon.png"


flutter:
  uses-material-design: true

  assets:
   - assets/images/logo.png